// <auto-generated />
using System;
using KotkovAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KotkovAPI.Migrations
{
    [DbContext(typeof(KotkovAPIContext))]
    [Migration("20251027203010_EditPhoneNumberSize")]
    partial class EditPhoneNumberSize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KotkovAPI.Models.Attendence", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("INT");

                    b.Property<int>("CourseId")
                        .HasColumnType("INT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INT");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StatusId");

                    b.ToTable("attendences", (string)null);
                });

            modelBuilder.Entity("KotkovAPI.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("DATE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(45)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("DATE");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INT");

                    b.Property<int>("TotalPlaces")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("KotkovAPI.Models.Progress", b =>
                {
                    b.Property<int>("TestId")
                        .HasColumnType("INT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INT");

                    b.Property<int>("Mark")
                        .HasColumnType("INT");

                    b.HasKey("TestId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("progresses", (string)null);
                });

            modelBuilder.Entity("KotkovAPI.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(45)");

                    b.HasKey("Id");

                    b.ToTable("statuses", (string)null);
                });

            modelBuilder.Entity("KotkovAPI.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("Id");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("KotkovAPI.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("Id");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("KotkovAPI.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("INT");

                    b.Property<int>("HighestMark")
                        .HasColumnType("INT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(45)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("tests", (string)null);
                });

            modelBuilder.Entity("KotkovAPI.Models.Attendence", b =>
                {
                    b.HasOne("KotkovAPI.Models.Course", "Course")
                        .WithMany("Attendences")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KotkovAPI.Models.Status", "Status")
                        .WithMany("Attendences")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KotkovAPI.Models.Student", "Student")
                        .WithMany("Attendences")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Status");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("KotkovAPI.Models.Course", b =>
                {
                    b.HasOne("KotkovAPI.Models.Teacher", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("KotkovAPI.Models.Progress", b =>
                {
                    b.HasOne("KotkovAPI.Models.Student", "Student")
                        .WithMany("Progresses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KotkovAPI.Models.Test", "Test")
                        .WithMany("Progresses")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("KotkovAPI.Models.Test", b =>
                {
                    b.HasOne("KotkovAPI.Models.Course", "Course")
                        .WithMany("Tests")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("KotkovAPI.Models.Course", b =>
                {
                    b.Navigation("Attendences");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("KotkovAPI.Models.Status", b =>
                {
                    b.Navigation("Attendences");
                });

            modelBuilder.Entity("KotkovAPI.Models.Student", b =>
                {
                    b.Navigation("Attendences");

                    b.Navigation("Progresses");
                });

            modelBuilder.Entity("KotkovAPI.Models.Teacher", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("KotkovAPI.Models.Test", b =>
                {
                    b.Navigation("Progresses");
                });
#pragma warning restore 612, 618
        }
    }
}
